#!/bin/zsh
udiskie &
picom --vsync --opengl &
/usr/bin/dunst & 
# flameshot & 
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/wireplumber &
xset r rate 230 45
redshift &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec dbus-launch i3
